id: IB22304C6
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:14:16.320492+00:00
last_modified: 2022-12-14 18:14:16.320500+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-100-001
  eft-text-version: 1.1.7 2020
  title: Toh_846-Threefold_Invocation_Ritual-v2
bases:
  B854:
    source_metadata: null
    order: 1
    base_file: B854.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
